# Generated by Django 5.1.6 on 2026-02-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('in_store_tasting', 'In-Store Tasting'), ('festival', 'Festival'), ('special_event', 'Special Event'), ('admin_hours', 'Admin Hours')], default='in_store_tasting', max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Duration of the event in minutes.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='distribution.account')),
                ('ambassador', models.ForeignKey(blank=True, limit_choices_to={'role': 'ambassador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_events', to=settings.AUTH_USER_MODEL)),
                ('ambassador_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'ambassador_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.company')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
    ]
