# Generated by Django 6.0.2 on 2026-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('recap_in_progress', 'Recap In Progress'), ('recap_submitted', 'Recap Submitted'), ('revision_requested', 'Revision Requested'), ('complete', 'Complete')], default='draft', max_length=30),
        ),
    ]
