# Generated by Django 5.1.6 on 2026-02-27 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercoveragearea'),
        ('catalog', '0002_initial'),
        ('events', '0002_update_account_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='ambassador_manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='events', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='revision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 min'), (15, '15 min'), (30, '30 min'), (45, '45 min')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tasting', 'Tasting'), ('festival', 'Festival'), ('admin', 'Admin')], default='tasting', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('recap_submitted', 'Recap Submitted'), ('revision_requested', 'Revision Requested'), ('complete', 'Complete')], default='draft', max_length=30),
        ),
    ]
