# Generated by Django 6.0.2 on 2026-03-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountitem_accountitempricehistory'),
        ('catalog', '0002_initial'),
        ('events', '0002_add_recap_in_progress_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recap_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_qr_codes_scanned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_samples_poured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_photos', to='accounts.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_event_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventItemRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bottles_sold', models.IntegerField(blank=True, null=True)),
                ('bottles_used_for_samples', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recaps', to='events.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_item_recaps', to='catalog.item')),
            ],
            options={
                'unique_together': {('event', 'item')},
            },
        ),
    ]
