# Generated by Django 5.1.6 on 2026-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ok_to_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='True for events created via historical import.'),
        ),
        migrations.AddField(
            model_name='event',
            name='legacy_ambassador_name',
            field=models.CharField(blank=True, default='', help_text='Ambassador name from historical import. Only set on imported events.', max_length=255),
        ),
    ]
