# Generated by Django 5.1.6 on 2026-03-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_import', '0001_initial_historicalimportbatch'),
        ('events', '0007_add_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='historical_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event_import.historicalimportbatch'),
        ),
    ]
