# Generated by Django 5.1.6 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_historical_batch_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('recap_in_progress', 'Recap In Progress'), ('recap_submitted', 'Recap Submitted'), ('revision_requested', 'Revision Requested'), ('complete', 'Complete'), ('ok_to_pay', 'Ok to Pay'), ('paid', 'Paid')], default='draft', max_length=30),
        ),
    ]
