# Generated by Django 5.1.6 on 2026-05-14 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_item_cases_per_batch_and_more'),
        ('core', '0013_distributor_inventory_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('projected', 'Projected'), ('actual', 'Actual')], default='projected', max_length=20)),
                ('external_po_number', models.CharField(blank=True, default='', max_length=100)),
                ('generated_by_algorithm', models.BooleanField(default=True, help_text='True when created by the production algorithm; False when manually entered.')),
                ('notes', models.TextField(blank=True, default='')),
                ('co_packer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_pos', to='catalog.copacker')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_pos', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_pos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production PO',
                'verbose_name_plural': 'Production POs',
                'ordering': ['-year', '-month', 'co_packer__name'],
            },
        ),
        migrations.CreateModel(
            name='OwnInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_cases', models.DecimalField(decimal_places=6, help_text='Quantity of this item on hand, in cases. Fractional values allowed (e.g., partial cases).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_inventory_snapshots', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_inventory_snapshots', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Own Inventory Snapshot',
                'verbose_name_plural': 'Own Inventory Snapshots',
                'ordering': ['-year', '-month', 'item__brand__name', 'item__name'],
                'unique_together': {('company', 'item', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProductionPOLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_count', models.PositiveIntegerField()),
                ('quantity_cases', models.DecimalField(decimal_places=6, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_po_lines', to='catalog.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionpo')),
            ],
            options={
                'verbose_name': 'Production PO Line',
                'verbose_name_plural': 'Production PO Lines',
                'ordering': ['item__brand__name', 'item__sort_order', 'item__name'],
                'unique_together': {('po', 'item')},
            },
        ),
    ]
