# Generated by Django 5.1.6 on 2026-05-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionpo',
            name='status',
            field=models.CharField(choices=[('projected', 'Projected'), ('actual', 'Actual'), ('complete', 'Complete')], default='projected', max_length=20),
        ),
    ]
