# Generated by Django 5.1.6 on 2026-06-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionpo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='owninventorysnapshot',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who most recently created or updated this snapshot value.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_snapshots_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
