# Generated by Django 6.0.2 on 2026-03-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercoveragearea'),
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_associated', models.DateField(help_text='Date this item was first seen at this account (set on creation, never updated).')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Most recent shelf price captured via event recap. Null until first recap.', max_digits=6, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_items', to='accounts.account')),
                ('item', models.ForeignKey(help_text='Always the internal productERP Item — never the raw distributor item code.', on_delete=django.db.models.deletion.CASCADE, related_name='account_items', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Account Item',
                'verbose_name_plural': 'Account Items',
                'ordering': ['account', 'item'],
                'unique_together': {('account', 'item')},
            },
        ),
        migrations.CreateModel(
            name='AccountItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='accounts.accountitem')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Null when set by the system during import; populated via recap submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Item Price History',
                'verbose_name_plural': 'Account Item Price Histories',
                'ordering': ['account_item', '-recorded_at'],
            },
        ),
    ]
