# Generated by Django 5.1.6 on 2026-03-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountitem_accountitempricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='distributor_route',
            field=models.CharField(blank=True, default='', help_text='Raw text, full value from import source.', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='third_party_id',
            field=models.CharField(blank=True, default='', help_text='Generic ID for future third-party system integrations.', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, default='', help_text='Raw text, no validation. Values vary by source.', max_length=100),
        ),
    ]
