# Generated by Django 5.1.6 on 2026-03-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_state_coverage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('is_tasting_contact', models.BooleanField(default=False, help_text='Primary contact for booking tastings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.account')),
            ],
            options={
                'ordering': ['-is_tasting_contact', 'name'],
            },
        ),
    ]
