# Generated by Django 5.1.6 on 2026-04-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_can_manage_account_notes_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountnote',
            name='note_type',
        ),
        migrations.RemoveField(
            model_name='accountnote',
            name='visit_date',
        ),
        migrations.DeleteModel(
            name='AccountNotePhoto',
        ),
    ]
