# Generated by Django 5.1.6 on 2026-04-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_note_type_visit_date_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountnote',
            name='is_task',
        ),
        migrations.RemoveField(
            model_name='accountnote',
            name='task_assignee',
        ),
        migrations.RemoveField(
            model_name='accountnote',
            name='task_priority',
        ),
    ]
