# Generated by Django 5.1.6 on 2026-06-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_task_fields_from_note'),
        ('distribution', '0018_seed_sort_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='distributor',
            field=models.ForeignKey(help_text='The distributor that services this account.', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='distribution.distributor'),
        ),
    ]
