# Generated by Django 5.1.6 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_distributor_groups_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='so_sequence_start',
            field=models.IntegerField(default=2006, help_text='Starting SO number for the first auto-assigned PO. Used once, then MAX+1 takes over.'),
        ),
    ]
