# Generated by Django 5.1.6 on 2026-03-22 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_state_coverage_type'),
        ('core', '0008_remove_ambassador_manager_report_access'),
        ('distribution', '0006_remove_distributor_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='distribution.distributor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('created_by', 'distributor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RouteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within this route. Lower values appear first.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_accounts', to='accounts.account')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_accounts', to='routes.route')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('route', 'account')},
            },
        ),
    ]
