# Generated by Django 5.1.6 on 2026-02-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
