# Generated by Django 5.1.6 on 2026-02-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_add_city_state_notes_to_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_normalized',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='True if this account was created automatically by a sales data import.'),
        ),
        migrations.AddField(
            model_name='account',
            name='city_normalized',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='county',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='merge_note',
            field=models.TextField(blank=True, help_text='Reason or notes captured when this account was merged.'),
        ),
        migrations.AddField(
            model_name='account',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If set, this account has been merged into the referenced account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_accounts', to='distribution.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='on_off_premise',
            field=models.CharField(blank=True, default='Unknown', help_text='ON, OFF, or Unknown.', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='state_normalized',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='vip_outlet_id',
            field=models.CharField(blank=True, help_text='VIP Outlet ID from distributor export. Reference only, not used as unique key.', max_length=100),
        ),
    ]
