# Generated by Django 5.1.6 on 2026-05-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_cases_per_pallet'),
        ('distribution', '0006_remove_distributor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='order_quantity_unit',
            field=models.CharField(blank=True, choices=[('pallets', 'Pallets'), ('cases', 'Cases')], help_text='Whether the order quantity is in pallets or cases.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='order_quantity_value',
            field=models.PositiveIntegerField(blank=True, help_text='Typical order size in pallets or cases. Leave blank if not yet configured.', null=True),
        ),
        migrations.CreateModel(
            name='DistributorItemProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_stock_cases', models.PositiveIntegerField(blank=True, null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_profiles', to='distribution.distributor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_profiles', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Distributor Item Profile',
                'verbose_name_plural': 'Distributor Item Profiles',
                'unique_together': {('distributor', 'item')},
            },
        ),
    ]
