# Generated by Django 5.1.6 on 2026-05-07 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_cases_per_pallet'),
        ('distribution', '0007_distributor_order_quantity_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoritemprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this distributor carries this item. When inactive, the item is hidden from inventory views and excluded from forecasts.'),
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_cases', models.PositiveIntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='distribution.distributor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Inventory Snapshot',
                'verbose_name_plural': 'Inventory Snapshots',
                'ordering': ['-year', '-month', 'distributor__name', 'item__name'],
                'unique_together': {('distributor', 'item', 'year', 'month')},
            },
        ),
    ]
