# Generated by Django 5.1.6 on 2026-05-11 21:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_distributor_inventory_permission'),
        ('distribution', '0008_distributoritemprofile_is_active_inventorysnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='quantity_cases',
            field=models.DecimalField(decimal_places=6, help_text='Quantity of this item on hand at the distributor, in cases. Fractional values allowed (e.g., partial cases).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='InventoryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('filename', models.CharField(max_length=500)),
                ('distributor_count', models.PositiveIntegerField()),
                ('snapshots_created', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_import_batches', to='core.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Import Batch',
                'verbose_name_plural': 'Inventory Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='distribution.inventoryimportbatch'),
        ),
    ]
