# Generated by Django 5.1.6 on 2026-05-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_cases_per_pallet'),
        ('distribution', '0009_alter_inventorysnapshot_quantity_cases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('projected', 'Projected'), ('actual', 'Actual')], default='projected', max_length=20)),
                ('external_po_number', models.CharField(blank=True, default='', max_length=100)),
                ('generated_by_algorithm', models.BooleanField(default=True, help_text='True when created by the order-generation algorithm; False when manually entered.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_pos_created', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='distribution.distributor')),
            ],
            options={
                'verbose_name': 'Distributor PO',
                'verbose_name_plural': 'Distributor POs',
                'ordering': ['-year', '-month', 'distributor__name'],
            },
        ),
        migrations.CreateModel(
            name='DistributorPOLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_cases', models.DecimalField(decimal_places=6, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='catalog.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='distribution.distributorpo')),
            ],
            options={
                'verbose_name': 'Distributor PO Line',
                'verbose_name_plural': 'Distributor PO Lines',
                'ordering': ['item__brand__name', 'item__sort_order', 'item__name'],
                'unique_together': {('po', 'item')},
            },
        ),
    ]
