# Generated by Django 5.1.6 on 2026-05-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_production_permission'),
        ('distribution', '0010_distributorpo_distributorpoline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_groups', to='core.company')),
                ('primary_distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_groups', to='distribution.distributor', unique=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='distributor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='distribution.distributorgroup'),
        ),
    ]
