# Generated by Django 5.1.6 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_distributorgroup_distributor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpo',
            name='so_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='Auto-assigned when PO is Submitted', null=True),
        ),
        migrations.AlterField(
            model_name='distributorpo',
            name='status',
            field=models.CharField(choices=[('projected', 'Projected'), ('actual', 'Actual'), ('submitted', 'Submitted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='projected', max_length=20),
        ),
    ]
