# Generated by Django 5.1.6 on 2026-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_distributorpo_so_number_alter_distributorpo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Short identifier for this distributor (e.g., SPDC). Auto-generated from name if left blank.', max_length=10),
        ),
    ]
