# Generated by Django 5.1.6 on 2026-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0015_regenerate_distributor_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpo',
            name='selected_for_projection',
            field=models.BooleanField(default=False, help_text='Whether this PO is selected in the inventory projection tool on the Distributor POs tab.'),
        ),
    ]
