# Generated by Django 5.1.6 on 2026-06-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_distributorpo_selected_for_projection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributorpo',
            options={'ordering': ['year', 'month', 'sort_position', 'distributor__name'], 'verbose_name': 'Distributor PO', 'verbose_name_plural': 'Distributor POs'},
        ),
        migrations.AddField(
            model_name='distributorpo',
            name='sort_position',
            field=models.IntegerField(default=0, help_text='Manual ordering position within the PO month (lower appears first). Renumbered on move.'),
        ),
    ]
