# Generated by Django 5.1.6 on 2026-06-02 23:14

from collections import defaultdict

from django.db import migrations

# Workflow status order (mirrors the lifecycle used elsewhere for ranking).
STATUS_WORKFLOW_ORDER = [
    'projected', 'actual', 'submitted', 'in_transit', 'delivered', 'invoiced', 'cancelled',
]


def seed_sort_position(apps, schema_editor):
    """Seed sort_position for existing POs.

    Within each (company, year, month) group, order by status-workflow rank then
    distributor name, and assign sort_position 1, 2, 3...
    """
    DistributorPO = apps.get_model('distribution', 'DistributorPO')
    rank = {s: i for i, s in enumerate(STATUS_WORKFLOW_ORDER)}

    groups = defaultdict(list)
    for po in DistributorPO.objects.select_related('distributor').all():
        company_id = po.distributor.company_id
        groups[(company_id, po.year, po.month)].append(po)

    for key, pos in groups.items():
        pos.sort(key=lambda p: (rank.get(p.status, 99), p.distributor.name))
        for idx, po in enumerate(pos, start=1):
            if po.sort_position != idx:
                po.sort_position = idx
                po.save(update_fields=['sort_position'])


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0017_alter_distributorpo_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_sort_position, reverse_code=migrations.RunPython.noop),
    ]
