# Generated by Django 5.1.6 on 2026-02-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='core.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.brand'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('brand', 'item_code')},
        ),
    ]
