# Generated by Django 5.1.6 on 2026-03-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['brand', 'sort_order', 'name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within this brand. Lower values appear first.'),
        ),
    ]
