# Generated by Django 5.1.6 on 2026-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_item_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cases_per_pallet',
            field=models.PositiveIntegerField(blank=True, help_text='Number of cases that fit on one pallet for this item. Used by the distributor inventory and forecasting tools.', null=True),
        ),
    ]
