# Generated by Django 5.1.6 on 2026-05-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_cases_per_pallet'),
        ('core', '0013_distributor_inventory_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cases_per_batch',
            field=models.PositiveIntegerField(blank=True, help_text='Number of cases produced in one batch. Used by production projections.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='production_safety_stock_cases',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum on-hand inventory to trigger production. Used by production projections.', null=True),
        ),
        migrations.CreateModel(
            name='CoPacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='co_packers', to='core.company')),
            ],
            options={
                'verbose_name': 'Co-Packer',
                'verbose_name_plural': 'Co-Packers',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='co_packer',
            field=models.ForeignKey(blank=True, help_text='The co-packer that produces this item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.copacker'),
        ),
    ]
