# Generated by Django 5.1.6 on 2026-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_co_packers_all_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forecast_current_inventory',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ad-hoc current on-hand inventory (cases) for PO projection planning. Not tied to inventory imports.', max_digits=10),
        ),
    ]
