# Generated by Django 5.1.6 on 2026-02-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('sales_data', 'Sales Data'), ('inventory_data', 'Inventory Data')], default='sales_data', max_length=20)),
                ('import_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('has_unmapped_items', 'Has Unmapped Items'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='catalog.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='core.company')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='distribution.distributor')),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-import_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_item_name', models.CharField(help_text='The item name exactly as it appeared in the import file.', max_length=500)),
                ('status', models.CharField(choices=[('unmapped', 'Unmapped'), ('mapped', 'Mapped'), ('ignored', 'Ignored')], default='unmapped', max_length=20)),
                ('brand', models.ForeignKey(help_text='Item mapping is scoped to a Brand within a Company.', on_delete=django.db.models.deletion.PROTECT, related_name='item_mappings', to='catalog.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_mappings', to='core.company')),
                ('mapped_item', models.ForeignKey(blank=True, help_text='The resolved catalog Item. Null while status is unmapped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_mappings', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Item Mapping',
                'verbose_name_plural': 'Item Mappings',
                'ordering': ['status', 'brand', 'raw_item_name'],
                'unique_together': {('brand', 'raw_item_name')},
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='distribution.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='core.company')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='imports.importbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='catalog.item')),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['company', 'sale_date'], name='imports_sal_company_902e8d_idx'), models.Index(fields=['account', 'sale_date'], name='imports_sal_account_261b07_idx'), models.Index(fields=['item', 'sale_date'], name='imports_sal_item_id_839246_idx')],
            },
        ),
    ]
