# Generated by Django 5.1.6 on 2026-02-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0003_add_phone_and_created_by_to_user'),
        ('distribution', '0003_account_address_normalized_account_auto_created_and_more'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmapping',
            options={'ordering': ['status', 'distributor', 'raw_item_name'], 'verbose_name': 'Item Mapping', 'verbose_name_plural': 'Item Mappings'},
        ),
        migrations.AlterUniqueTogether(
            name='itemmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='accounts_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='records_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='records_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemmapping',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='The distributor this mapping applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_mappings', to='distribution.distributor'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='catalog.brand'),
        ),
        migrations.AlterField(
            model_name='itemmapping',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand context for filtering the mapped item dropdown.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_mappings', to='catalog.brand'),
        ),
        migrations.AlterField(
            model_name='itemmapping',
            name='raw_item_name',
            field=models.CharField(help_text='The item code exactly as it appeared in the import file.', max_length=500),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='quantity',
            field=models.IntegerField(help_text='Quantity sold. May be negative for returns/corrections.'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmapping',
            unique_together={('company', 'distributor', 'raw_item_name')},
        ),
    ]
