# Generated by Django 6.0.2 on 2026-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_remove_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='account_items_created',
            field=models.IntegerField(default=0),
        ),
    ]
