# Generated by Django 5.1.6 on 2026-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importbatch_account_items_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='accounts_reactivated',
            field=models.IntegerField(default=0),
        ),
    ]
